# https://stackoverflow.com/questions/41916656/how-to-use-travis-ci-to-build-modern-c-using-modern-cmake
dist: trusty
sudo: required
language: cpp
compiler:
  - gcc
script:
  - mkdir build
  - cd build
  - ccmake ../
  - make