# https://stackoverflow.com/questions/41916656/how-to-use-travis-ci-to-build-modern-c-using-modern-cmake
dist: trusty
sudo: required
language: cpp
addons:
  apt:
    packages:
      - cmake
compiler:
  - gcc
before_script:
  - mkdir cmake
  - cd cmake
  - wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3.tar.gz
  - tar -xvf cmake-3.13.3.tar.gz
script:
  - CMakeLists.txt -B . -G "Unix Makefiles"
  - make