# https://stackoverflow.com/questions/41916656/how-to-use-travis-ci-to-build-modern-c-using-modern-cmake
dist: trusty
sudo: required
language: cpp
addons:
  apt:
    packages:
      - cmake
      - cmake-data
compiler:
  - gcc
script:
  - cmake CMakeLists.txt -B . -G "Unix Makefiles"
  - make