# https://stackoverflow.com/questions/41916656/how-to-use-travis-ci-to-build-modern-c-using-modern-cmake
dist: trusty
sudo: required
language: cpp
addons:
  apt:
    packages:
      - cmake
compiler:
  - gcc
before_script:
  - whereis cmake
  - /usr/bin/cmake --version
script:
  - /usr/bin/cmake CMakeLists.txt -B . -G "Unix Makefiles"
  - make